spring.application.name=secureauth-api

spring.datasource.url=jdbc:postgresql://localhost:5433/secureauth_db
spring.datasource.username=postgres
spring.datasource.password=oussama

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=e90TIIDcXoRjliy5erktCcZFkmQ1PdW80hHh7CAeWSc=
jwt.expiration=3600000
jwt.refresh-expiration=604800000
server.port=8080