spring.application.name=secureauth-api

spring.datasource.url=jdbc:postgresql://localhost:5433/secureauth_db
spring.datasource.username=postgres
spring.datasource.password=oussama

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=e90TIIDcXoRjliy5erktCcZFkmQ1PdW80hHh7CAeWSc=
jwt.expiration=3600000
jwt.refresh-expiration=604800000
server.port=8080

app.admin.email=admin@secureauth.com
app.admin.password=Admin12345

app.password-reset.expiration=900000
app.email-verification.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oussamaksantini@gmail.com
spring.mail.password=aefmjxwlcalgysnb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true